# Generated by Django 5.0.6 on 2024-06-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('idname', models.IntegerField()),
                ('numcon', models.IntegerField()),
                ('cargo', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
